### ISSUE TITLE
Remove clause of incompatibility license

### ISSUE THREAD

**Issue by petitlapin** [shubhendusaurabh/draughts.js#7]
Hi,
I'm one of GCompris developers'. We are using your checkers library in our software (released under GPLv3+ licence) and we just noticed that in the licence of your library, there is the "Exhibit B" ("Incompatible With Secondary Licenses") which prevents us to provide GCompris+shipping of your library under GPLv3 license only (https://invent.kde.org/education/gcompris/-/tree/master/src/activities/checkers).

Is there a reason to have this clause or can you remove it? I can make a PR to remove it if it is ok with you

**Comment by shubhendusaurabh** [comment]
No reason anymore as i abandoned the project for which it was made. Please raise PR with more permissible license. 
I have invited you as collaborator, feel free to accept or decline, if you want to help maintain and using it.
Thanks.

**Comment by petitlapin** [comment]
Thank you, I've accepted the invitation.
I'll make a PR soon for the clause

**Comment by petitlapin** [comment]
After reading https://www.mozilla.org/en-US/MPL/2.0/FAQ/ (especially Q14 and Q25), as long as the "Exhibit B" is not in the source code (so the js file), there is no issue and we can use it in a GPL3 software without double-licensing...

Well, at least you found someone who will help maintening :)
