### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by Richienb** [shubhendusaurabh/draughts.js#8]
I can help maintain draughts.js, completing all of the todos left.

Please add me as a maintainer on Github and on npm.

// @shubhendusaurabh

**Comment by shubhendusaurabh** [comment]
Added

**Comment by Richienb** [comment]
@shubhendusaurabh I'm trying to rewrite the move validation but to do so, I need to know what **version** of Draughts we are supposed to be using.

**Comment by shubhendusaurabh** [comment]
@Richienb I think I had English draughts in mind when i started this project but long term aim was to cover all major versions through configuration.

But soon started another repo with support for 10x10 board: https://github.com/shubhendusaurabh/checkers.js as the bitboard logic was different and handling rule variations would increase complexity.

**Comment by Richienb** [comment]
@shubhendusaurabh Perhaps we can accept a `gameType` option which initialises different validation engines.

**Comment by shubhendusaurabh** [comment]
@Richienb yes, that's a good idea. with some default engine if no option passed.

**Comment by Richienb** [comment]
I've created the `refactor` branch and added some empty functions to https://github.com/shubhendusaurabh/draughts.js/blob/refactor/source/gameTypes/english.ts
